version: '3'

services:
  database:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_ROOT_PASSWORD=rootpassword
    # volumes:
    #   - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  php-apache:
    build: .
    container_name: php-apache
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    depends_on:
      - database

# volumes:
#   dbdata:
